#!/bin/bash

(git co master; cd guncat; ./build man; ./build distclean; git co gh-pages)

yodl2html index.yo || exit 1

echo -n "ci change to index.html etc., push the result and co master [y/n] ? "
read yesno

if [ "$yesno" == "y" ] ; then
    RELEASE=`head -n1 ../wip/release.yo | 
		sed 's/SUBST(_CurVers_)(\(.*\))/\1/'`
    gi ci -am "updated index.html for gh-pages, release $RELEASE"
    git push
    git co master
fi


