#!/bin/bash

echo -n "Need to (re)create wip/release.yo and wip/guncat.1.html [y/n] ? "
read yesno

if [ "$yesno" == "y" ] ; then
    git co master; 
    cd guncat
    ./build man 
    ./build std
    ./build github
    ./build distclean
    cd ..
    git co gh-pages
fi

cp -r ../wip/changelog.txt ../wip/${_product_}.1.html .

yodl2html index.yo || exit 1	

echo "Running 'git st': no untracked files or ignorable files should be shown"
git st

echo

echo -n "ci change to index.html etc., push the result and co master [y/n] ? "
read yesno

if [ "$yesno" == "y" ] ; then
    RELEASE=`head -n1 ../wip/release.yo | 
		sed 's/SUBST(_CurVers_)(\(.*\))/\1/'`
    git ci -am "updated index.html for gh-pages, release $RELEASE"
    git push
    git co master
fi


